# Generated by Django 3.2 on 2021-04-24 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Patient_No', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Prescription_Date', models.DateField(default=datetime.date.today)),
                ('Patient_Weight', models.FloatField(max_length=10)),
                ('Patient_Height', models.FloatField(max_length=10)),
                ('Is_Patient_Admitted', models.BooleanField(default=False)),
                ('Patient_Mobile_No', models.BigIntegerField()),
                ('Patient_Image', models.ImageField(upload_to='./Images')),
                ('Patient_Condition_Description', models.TextField(max_length=200)),
            ],
        ),
    ]
