# Generated by Django 3.2 on 2021-04-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Patient_Age',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Patient_Allergies',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Patient_Gender',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Patient_Medicine',
        ),
    ]
