# Generated by Django 3.2 on 2021-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0002_auto_20210428_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Is_Patient_Admitted',
            field=models.CharField(default='off', max_length=5),
        ),
    ]
