# Generated by Django 3.2 on 2021-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0003_alter_prescription_is_patient_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Is_Patient_Admitted',
            field=models.BooleanField(default=False),
        ),
    ]
